[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
## [{{ version }}] - {{ timestamp | date(format=\"%Y-%m-%d\") }}

{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.scope %} *({{commit.scope}})*{% endif %}
{% endfor %}

{% endfor %}
"""
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^style", group = "Styling" },
    { message = "^refactor", group = "Code Refactoring" },
    { message = "^perf", group = "Performance Improvements" },
    { message = "^test", group = "Tests" },
    { message = "^build", group = "Build System" },
    { message = "^ci", group = "Continuous Integration" },
    { message = "^chore", group = "Chores" },
    { message = "^revert", group = "Reverts" },
]
filter_commits = true
